version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mutation-service:
    build: ./mutation-service
    container_name: mutation-service
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017/mdid

  query-service:
    build: ./query-service
    container_name: query-service
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: mongodb://mongo:27017/mdid

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - mutation-service
      - query-service
    environment:
      - MUTATION_SERVICE_URL=http://mutation-service:3000
      - QUERY_SERVICE_URL=http://query-service:3000

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3003:3000"
    depends_on:
      - mutation-service
    environment:
      - JWT_SECRET=pruebaDeClave
      - MUTATION_SERVICE_URL=http://mutation-service:3000

volumes:
  mongo-data:
